In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_validate,train_test_split,KFold,LeaveOneOut,cross_val_score,cross_val_predict
from matplotlib import pyplot as plt
from sklearn.linear_model import Ridge 
from sklearn.preprocessing import StandardScaler 
import seaborn as sns
from scipy import stats

In [19]:
#Read data
url = 'https://raw.githubusercontent.com/orangeczw/ML_team_Name/master/Task_1a/train.csv'
train = pd.read_csv(url, error_bad_lines=False)
y = train.iloc[:,1].copy()
X = train.iloc[:,2:].copy()

#See if there's NA value
X.isna().any()

x1     False
x2     False
x3     False
x4     False
x5     False
x6     False
x7     False
x8     False
x9     False
x10    False
x11    False
x12    False
x13    False
dtype: bool

In [20]:
#Using Pearson Correlation and find out highly correlated independent variables  
cor = train.corr()
cor[abs(cor)>0.8]

,Id,y,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13
Id,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
y,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
x1,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
x2,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
x3,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
x4,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
x5,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
x6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
x7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
x8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
x9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.910228,NaN,NaN,NaN
x10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.910228,1.000000,NaN,NaN,NaN
x11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
x12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
x13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [21]:
#Correlation with output variable
cor_target = abs(cor["y"])
print(cor_target)

Id     0.044615
y      1.000000
x1     0.385832
x2     0.360445
x3     0.483725
x4     0.175260
x5     0.427321
x6     0.695360
x7     0.376955
x8     0.249929
x9     0.381626
x10    0.468536
x11    0.507787
x12    0.333461
x13    0.737663
Name: y, dtype: float64

In [22]:
X_del = X.drop(['x9'], axis=1)
#delete x9 since cor(x9,x10) = 0.910228, and x9 is less correlated with y than x10.

In [23]:
penalty = [0.01,0.1,1,10,100]
RMSE = []

for lmd in penalty:
    model = Ridge(alpha = lmd, normalize = False, tol = 0.001, solver ='auto', random_state = 42)
    cv_results = cross_validate(model, X_del, y, cv=10,
                            n_jobs=-1,scoring=('neg_mean_squared_error'))
    result = np.sqrt(np.abs(cv_results["test_score"]).mean())
    RMSE.append(result)
    
RMSE = pd.DataFrame(RMSE) 
np.savetxt("submission_1a.csv",np.array(RMSE))
print(RMSE)

          0
0  4.993136
1  4.992714
2  5.000570
3  5.038338
4  5.152825